Vagrant.configure("2") do |config|
    config.vm.network "forwarded_port", guest: 9000, host: 9000
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.define "controle" do |controle|
        controle.vm.box = "shekeriev/debian-11"
        controle.vm.hostname = "controle" 
	    controle.vm.provider "virtualbox" do |vb|
	    	vb.name = "controle"
 	  	    vb.memory = "4098"
	  	    vb.cpus = 2
        end
    end
end